services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    # environment:
    #   - INFLUXDB_DB=influx
    #   - INFLUXDB_ADMIN_USER=admin
    #   - INFLUXDB_ADMIN_PASSWORD=admin
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=agin
      - DOCKER_INFLUXDB_INIT_BUCKET=usage
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=influx-configs
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=yOm3TCJl4a-nb1VKRAF11Qt47VhEB3jskYa0z50CknXLwRiyTWs_VXgswYDtBy3E2da6auDXUvPEeaTHpmeYMg==
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx:/var/lib/influxdb2
      - ./config/influx:/etc/influxdb2
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=admin
    #   - MONGODB_INITDB_ROOT_PASSWORD=adminadmin
    volumes:
      - type: bind
        source: ./data/mongo
        target: /data/db
    ports:
      - 27017:27017
    restart: always
    user: 1000:1000
